# User FSM states
IDLE = ""
LEGAL_DOCS = "legal_docs"
LEGAL_CHECKBOXES = "legal_checkboxes"
CLINIC_ACK = "clinic_ack"
REG_NAME = "reg_name"
REG_PHONE = "reg_phone"
REG_EMAIL = "reg_email"
REG_CITY = "reg_city"

PET_SPECIES = "pet_species"
PET_NAME = "pet_name"
PET_AGE = "pet_age"
PET_SEX = "pet_sex"
PET_WEIGHT = "pet_weight"
PET_CAST = "pet_cast"
PET_CHRONIC = "pet_chronic"
PET_PAST = "pet_past"
PET_MEDS = "pet_meds"
PET_ALLERGY = "pet_allergy"

TICKET_WORSENING = "ticket_worsening"
TICKET_EMERGENCY = "ticket_emergency"
TICKET_COMPLAINTS = "ticket_complaints"
TICKET_STARTED = "ticket_started"
TICKET_ACTIVITY = "ticket_activity"
TICKET_APPETITE = "ticket_appetite"
TICKET_STOOL = "ticket_stool"
TICKET_URINE = "ticket_urine"
TICKET_TEMP = "ticket_temp"
TICKET_ATTACH = "ticket_attach"
TICKET_CONFIRM = "ticket_confirm"

SUB_CHOOSE_PLAN = "sub_choose_plan"
SUB_CHOOSE_PERIOD = "sub_choose_period"
SUB_CHECKOUT_CONSENT = "sub_checkout_consent"
PAYMENT_PENDING = "payment_pending"
CANCEL_AUTO_RENEW = "cancel_auto_renew"

DOSAGE_WAIT_QUERY = "dosage_wait_query"
DOSAGE_PICK = "dosage_pick"
DOSAGE_QA = "dosage_qa"
DOSAGE_ASK_AI = "dosage_ask_ai"

CALC_WAIT_TEXT = "calc_wait_text"
CALC_CONFIRM = "calc_confirm"
CALC_MISSING = "calc_missing"
